#!/bin/bash

SAT=${1// /_} # Substitude space on upload
FILEKEY=$2

AUDIO_DIR=${WX_GROUND_DIR}/audio
IMAGE_DIR=$WX_GROUND_DIR/images
FTP_DIRECTORY=$WX_GROUND_FTP_DIR
AUDIO_FILE=${FILEKEY}.wav
AUDIO_FILE_DIR=${AUDIO_DIR}/${FILEKEY}.wav
IQ_FILE=${FILEKEY}.iq
IQ_FILE_DIR=${AUDIO_DIR}/${FILEKEY}.iq
MAP_FILE=${FILEKEY}-map.png
MAP_FILE_DIR=${IMAGE_DIR}/${FILEKEY}-map.png
ZA_FILE=${FILEKEY}-ZA.png
ZA_FILE_DIR=${IMAGE_DIR}/${FILEKEY}-ZA.png
NO_FILE=${FILEKEY}-NO.png
NO_FILE_DIR=${IMAGE_DIR}/${FILEKEY}-NO.png
MSA_FILE=${FILEKEY}-MSA.png
MSA_FILE_DIR=${IMAGE_DIR}/${FILEKEY}-MSA.png
MCIR_FILE=${FILEKEY}-MCIR.png
MCIR_FILE_DIR=${IMAGE_DIR}/${FILEKEY}-MCIR.png
THERM_FILE=${FILEKEY}-THERM.png
THERM_FILE_DIR=${IMAGE_DIR}/${FILEKEY}-THERM.png


DATE=`date +%Y-%m-%d`
HOST=$WX_GROUND_FTP_SERVER
USER=$WX_GROUND_FTP_USER
PASSWD=$WX_GROUND_FTP_PASS

ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
mkdir $FTP_DIRECTORY
cd $FTP_DIRECTORY
mkdir $SAT
cd $SAT
mkdir $DATE
cd $DATE
binary
put $AUDIO_FILE_DIR $AUDIO_FILE
put $IQ_FILE_DIR $IQ_FILE
put $MAP_FILE_DIR $MAP_FILE
put $ZA_FILE_DIR $ZA_FILE
put $NO_FILE_DIR $NO_FILE
put $MSA_FILE_DIR $MSA_FILE
put $MCIR_FILE_DIR $MCIR_FILE
put $THERM_FILE_DIR $THERM_FILE
quit
END_SCRIPT

# Send web hook to IFTTT
if [[ "$WX_GROUND_IFTTT_WEBHOOK" != "" ]]; then
  IMAGE_URL="${WX_GROUND_FTP_URL}/${FTP_DIRECTORY}/${SAT}/${DATE}/${FILEKEY}-MSA.png"
  HUMAN_TIME=`date +%H:%M`
  curl -X POST -H "Content-Type: application/json" -d '{"value1":"'"${SAT}"'","value2":"'"${HUMAN_TIME}"'","value3":"'"${IMAGE_URL}"'"}' ${WX_GROUND_IFTTT_WEBHOOK}
fi
