#!/bin/bash

SAT=$1
FILEKEY=$2

AUDIO_DIR=${WX_GROUND_DIR}/audio
IMAGE_DIR=$WX_GROUND_DIR/images
FTP_DIRECTORY=$WX_GROUND_FTP_DIR
AUDIO_FILE=${AUDIO_DIR}/${FILEKEY}.wav
IQ_FILE=${AUDIO_DIR}/${FILEKEY}.iq
MAP_FILE=${IMAGE_DIR}/${FILEKEY}-map.png
ZA_FILE=${IMAGE_DIR}/${FILEKEY}-ZA.png
NO_FILE=${IMAGE_DIR}/${FILEKEY}-NO.png
MSA_FILE=${IMAGE_DIR}/${FILEKEY}-MSA.png
MCIR_FILE=${IMAGE_DIR}/${FILEKEY}-MCIR.png
THERM_FILE=${IMAGE_DIR}/${FILEKEY}-THERM.png


DATE=`date +%Y-%m-%d`
HOST=$WX_GROUND_FTP_SERVER
USER=$WX_GROUND_FTP_USER
PASSWD=$WX_GROUND_FTP_PASS

ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
mkdir $FTP_DIRECTORY
cd $FTP_DIRECTORY
mkdir $SAT
cd $SAT
mkdir $DATE
cd $DATE
binary
put $AUDIO_FILE
put $IQ_FILE
put $MAP_FILE
put $ZA_FILE
put $NO_FILE
put $MSA_FILE
put $MCIR_FILE
put $THERM_FILE
quit
END_SCRIPT
exit 0
